version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_URL: http://localhost:8080
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    networks:
      - app-network

  backend:
    build: ./bpBackend/
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/bakalarka
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=matko123
    networks:
      - app-network

  database:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: bakalarka
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: matko123
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network

  ldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      - LDAP_ORGANISATION=ExampleOrg
      - LDAP_DOMAIN=example.com
      - LDAP_ADMIN_PASSWORD=admin
    ports:
      - "389:389" 
      - "636:636"   
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    networks:
      - app-network

networks:
  app-network:

volumes:
  pg_data:
  ldap_data:
  ldap_config:
